services:
  - type: web
    name: lynceus-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: ALLOWED_ORIGINS
        sync: false
    healthCheckPath: /api/health
